name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/risk-monitor-app:amd64 -f Dockerfile.local .
    
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/risk-monitor-app:amd64
